// Auto-generated types for Supabase database
// These types are based on the schema defined in supabase_schema.sql

export type SubscriptionTier = 'free_trial' | 'basic' | 'pro' | 'ultra_pro';
export type SubscriptionStatus = 'active' | 'cancelled' | 'expired' | 'pending';
export type UserRole = 'user' | 'admin';
export type LeadStatus = 'new' | 'contacted' | 'responded' | 'converted' | 'rejected';
export type EmailStatus = 'pending' | 'sent' | 'delivered' | 'opened' | 'clicked' | 'bounced' | 'failed';
export type CampaignStatus = 'draft' | 'scheduled' | 'sending' | 'completed' | 'paused';
export type WebsiteScore = 'good' | 'average' | 'poor' | 'no_website';

export interface Database {
    public: {
        Tables: {
            subscription_plans: {
                Row: {
                    id: string;
                    name: string;
                    tier: SubscriptionTier;
                    price_monthly: number;
                    price_yearly: number | null;
                    leads_per_month: number;
                    emails_per_month: number;
                    templates_limit: number;
                    can_export_csv: boolean;
                    priority_support: boolean;
                    trial_days: number;
                    features: string[];
                    is_active: boolean;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    name: string;
                    tier: SubscriptionTier;
                    price_monthly?: number;
                    price_yearly?: number | null;
                    leads_per_month?: number;
                    emails_per_month?: number;
                    templates_limit?: number;
                    can_export_csv?: boolean;
                    priority_support?: boolean;
                    trial_days?: number;
                    features?: string[];
                    is_active?: boolean;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    name?: string;
                    tier?: SubscriptionTier;
                    price_monthly?: number;
                    price_yearly?: number | null;
                    leads_per_month?: number;
                    emails_per_month?: number;
                    templates_limit?: number;
                    can_export_csv?: boolean;
                    priority_support?: boolean;
                    trial_days?: number;
                    features?: string[];
                    is_active?: boolean;
                    created_at?: string;
                    updated_at?: string;
                };
            };
            user_profiles: {
                Row: {
                    id: string;
                    email: string;
                    full_name: string | null;
                    phone: string | null;
                    company_name: string | null;
                    avatar_url: string | null;
                    role: UserRole;
                    subscription_tier: SubscriptionTier;
                    subscription_status: SubscriptionStatus;
                    subscription_start_date: string;
                    subscription_end_date: string | null;
                    leads_used_this_month: number;
                    emails_sent_this_month: number;
                    usage_reset_date: string;
                    is_active: boolean;
                    last_login_at: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id: string;
                    email: string;
                    full_name?: string | null;
                    phone?: string | null;
                    company_name?: string | null;
                    avatar_url?: string | null;
                    role?: UserRole;
                    subscription_tier?: SubscriptionTier;
                    subscription_status?: SubscriptionStatus;
                    subscription_start_date?: string;
                    subscription_end_date?: string | null;
                    leads_used_this_month?: number;
                    emails_sent_this_month?: number;
                    usage_reset_date?: string;
                    is_active?: boolean;
                    last_login_at?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    email?: string;
                    full_name?: string | null;
                    phone?: string | null;
                    company_name?: string | null;
                    avatar_url?: string | null;
                    role?: UserRole;
                    subscription_tier?: SubscriptionTier;
                    subscription_status?: SubscriptionStatus;
                    subscription_start_date?: string;
                    subscription_end_date?: string | null;
                    leads_used_this_month?: number;
                    emails_sent_this_month?: number;
                    usage_reset_date?: string;
                    is_active?: boolean;
                    last_login_at?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
            };
            user_subscriptions: {
                Row: {
                    id: string;
                    user_id: string;
                    plan_id: string;
                    tier: SubscriptionTier;
                    status: SubscriptionStatus;
                    amount_paid: number | null;
                    payment_method: string | null;
                    payment_reference: string | null;
                    start_date: string;
                    end_date: string | null;
                    cancelled_at: string | null;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    user_id: string;
                    plan_id: string;
                    tier: SubscriptionTier;
                    status?: SubscriptionStatus;
                    amount_paid?: number | null;
                    payment_method?: string | null;
                    payment_reference?: string | null;
                    start_date?: string;
                    end_date?: string | null;
                    cancelled_at?: string | null;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    user_id?: string;
                    plan_id?: string;
                    tier?: SubscriptionTier;
                    status?: SubscriptionStatus;
                    amount_paid?: number | null;
                    payment_method?: string | null;
                    payment_reference?: string | null;
                    start_date?: string;
                    end_date?: string | null;
                    cancelled_at?: string | null;
                    created_at?: string;
                };
            };
            smtp_configs: {
                Row: {
                    id: string;
                    user_id: string;
                    name: string;
                    host: string;
                    port: number;
                    username: string;
                    password_encrypted: string;
                    from_email: string;
                    from_name: string | null;
                    use_tls: boolean;
                    is_verified: boolean;
                    is_default: boolean;
                    last_used_at: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    user_id: string;
                    name: string;
                    host: string;
                    port?: number;
                    username: string;
                    password_encrypted: string;
                    from_email: string;
                    from_name?: string | null;
                    use_tls?: boolean;
                    is_verified?: boolean;
                    is_default?: boolean;
                    last_used_at?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    user_id?: string;
                    name?: string;
                    host?: string;
                    port?: number;
                    username?: string;
                    password_encrypted?: string;
                    from_email?: string;
                    from_name?: string | null;
                    use_tls?: boolean;
                    is_verified?: boolean;
                    is_default?: boolean;
                    last_used_at?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
            };
            lead_searches: {
                Row: {
                    id: string;
                    user_id: string;
                    search_name: string | null;
                    country: string;
                    state: string | null;
                    city: string | null;
                    area: string | null;
                    business_type: string;
                    client_need: string | null;
                    radius_km: number;
                    search_query: Record<string, unknown>;
                    results_count: number;
                    status: string;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    user_id: string;
                    search_name?: string | null;
                    country: string;
                    state?: string | null;
                    city?: string | null;
                    area?: string | null;
                    business_type: string;
                    client_need?: string | null;
                    radius_km?: number;
                    search_query?: Record<string, unknown>;
                    results_count?: number;
                    status?: string;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    user_id?: string;
                    search_name?: string | null;
                    country?: string;
                    state?: string | null;
                    city?: string | null;
                    area?: string | null;
                    business_type?: string;
                    client_need?: string | null;
                    radius_km?: number;
                    search_query?: Record<string, unknown>;
                    results_count?: number;
                    status?: string;
                    created_at?: string;
                };
            };
            leads: {
                Row: {
                    id: string;
                    user_id: string;
                    search_id: string | null;
                    business_name: string;
                    business_type: string | null;
                    description: string | null;
                    email: string | null;
                    phone: string | null;
                    owner_name: string | null;
                    address: string | null;
                    city: string | null;
                    state: string | null;
                    country: string | null;
                    postal_code: string | null;
                    latitude: number | null;
                    longitude: number | null;
                    website_url: string | null;
                    has_website: boolean;
                    website_score: WebsiteScore;
                    is_mobile_responsive: boolean | null;
                    has_ssl: boolean | null;
                    page_speed_score: number | null;
                    design_age_score: number | null;
                    analysis_notes: string | null;
                    last_analyzed_at: string | null;
                    status: LeadStatus;
                    notes: string | null;
                    tags: string[] | null;
                    source: string;
                    source_id: string | null;
                    raw_data: Record<string, unknown> | null;
                    // Enhanced contact fields
                    alternate_phone: string | null;
                    whatsapp_number: string | null;
                    facebook_url: string | null;
                    instagram_url: string | null;
                    linkedin_url: string | null;
                    google_maps_url: string | null;
                    // Enhanced business details
                    business_hours: Record<string, string> | null;
                    google_rating: number | null;
                    review_count: number;
                    employee_count: string | null;
                    year_established: number | null;
                    business_subcategory: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    user_id: string;
                    search_id?: string | null;
                    business_name: string;
                    business_type?: string | null;
                    description?: string | null;
                    email?: string | null;
                    phone?: string | null;
                    owner_name?: string | null;
                    address?: string | null;
                    city?: string | null;
                    state?: string | null;
                    country?: string | null;
                    postal_code?: string | null;
                    latitude?: number | null;
                    longitude?: number | null;
                    website_url?: string | null;
                    has_website?: boolean;
                    website_score?: WebsiteScore;
                    is_mobile_responsive?: boolean | null;
                    has_ssl?: boolean | null;
                    page_speed_score?: number | null;
                    design_age_score?: number | null;
                    analysis_notes?: string | null;
                    last_analyzed_at?: string | null;
                    status?: LeadStatus;
                    notes?: string | null;
                    tags?: string[] | null;
                    source?: string;
                    source_id?: string | null;
                    raw_data?: Record<string, unknown> | null;
                    // Enhanced contact fields
                    alternate_phone?: string | null;
                    whatsapp_number?: string | null;
                    facebook_url?: string | null;
                    instagram_url?: string | null;
                    linkedin_url?: string | null;
                    google_maps_url?: string | null;
                    // Enhanced business details
                    business_hours?: Record<string, string> | null;
                    google_rating?: number | null;
                    review_count?: number;
                    employee_count?: string | null;
                    year_established?: number | null;
                    business_subcategory?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    user_id?: string;
                    search_id?: string | null;
                    business_name?: string;
                    business_type?: string | null;
                    description?: string | null;
                    email?: string | null;
                    phone?: string | null;
                    owner_name?: string | null;
                    address?: string | null;
                    city?: string | null;
                    state?: string | null;
                    country?: string | null;
                    postal_code?: string | null;
                    latitude?: number | null;
                    longitude?: number | null;
                    website_url?: string | null;
                    has_website?: boolean;
                    website_score?: WebsiteScore;
                    is_mobile_responsive?: boolean | null;
                    has_ssl?: boolean | null;
                    page_speed_score?: number | null;
                    design_age_score?: number | null;
                    analysis_notes?: string | null;
                    last_analyzed_at?: string | null;
                    status?: LeadStatus;
                    notes?: string | null;
                    tags?: string[] | null;
                    source?: string;
                    source_id?: string | null;
                    raw_data?: Record<string, unknown> | null;
                    // Enhanced contact fields
                    alternate_phone?: string | null;
                    whatsapp_number?: string | null;
                    facebook_url?: string | null;
                    instagram_url?: string | null;
                    linkedin_url?: string | null;
                    google_maps_url?: string | null;
                    // Enhanced business details
                    business_hours?: Record<string, string> | null;
                    google_rating?: number | null;
                    review_count?: number;
                    employee_count?: string | null;
                    year_established?: number | null;
                    business_subcategory?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
            };
            email_templates: {
                Row: {
                    id: string;
                    user_id: string | null;
                    name: string;
                    subject: string;
                    body_html: string;
                    body_text: string | null;
                    variables: string[];
                    is_default: boolean;
                    use_count: number;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    user_id?: string | null;
                    name: string;
                    subject: string;
                    body_html: string;
                    body_text?: string | null;
                    variables?: string[];
                    is_default?: boolean;
                    use_count?: number;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    user_id?: string | null;
                    name?: string;
                    subject?: string;
                    body_html?: string;
                    body_text?: string | null;
                    variables?: string[];
                    is_default?: boolean;
                    use_count?: number;
                    created_at?: string;
                    updated_at?: string;
                };
            };
            email_campaigns: {
                Row: {
                    id: string;
                    user_id: string;
                    template_id: string | null;
                    smtp_config_id: string | null;
                    name: string;
                    subject: string;
                    body_html: string;
                    body_text: string | null;
                    status: CampaignStatus;
                    total_recipients: number;
                    sent_count: number;
                    delivered_count: number;
                    opened_count: number;
                    clicked_count: number;
                    bounced_count: number;
                    failed_count: number;
                    scheduled_at: string | null;
                    started_at: string | null;
                    completed_at: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    user_id: string;
                    template_id?: string | null;
                    smtp_config_id?: string | null;
                    name: string;
                    subject: string;
                    body_html: string;
                    body_text?: string | null;
                    status?: CampaignStatus;
                    total_recipients?: number;
                    sent_count?: number;
                    delivered_count?: number;
                    opened_count?: number;
                    clicked_count?: number;
                    bounced_count?: number;
                    failed_count?: number;
                    scheduled_at?: string | null;
                    started_at?: string | null;
                    completed_at?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    user_id?: string;
                    template_id?: string | null;
                    smtp_config_id?: string | null;
                    name?: string;
                    subject?: string;
                    body_html?: string;
                    body_text?: string | null;
                    status?: CampaignStatus;
                    total_recipients?: number;
                    sent_count?: number;
                    delivered_count?: number;
                    opened_count?: number;
                    clicked_count?: number;
                    bounced_count?: number;
                    failed_count?: number;
                    scheduled_at?: string | null;
                    started_at?: string | null;
                    completed_at?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
            };
            campaign_leads: {
                Row: {
                    id: string;
                    campaign_id: string;
                    lead_id: string;
                    personalized_subject: string | null;
                    personalized_body: string | null;
                    status: EmailStatus;
                    sent_at: string | null;
                    opened_at: string | null;
                    clicked_at: string | null;
                    error_message: string | null;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    campaign_id: string;
                    lead_id: string;
                    personalized_subject?: string | null;
                    personalized_body?: string | null;
                    status?: EmailStatus;
                    sent_at?: string | null;
                    opened_at?: string | null;
                    clicked_at?: string | null;
                    error_message?: string | null;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    campaign_id?: string;
                    lead_id?: string;
                    personalized_subject?: string | null;
                    personalized_body?: string | null;
                    status?: EmailStatus;
                    sent_at?: string | null;
                    opened_at?: string | null;
                    clicked_at?: string | null;
                    error_message?: string | null;
                    created_at?: string;
                };
            };
            email_logs: {
                Row: {
                    id: string;
                    user_id: string;
                    campaign_id: string | null;
                    lead_id: string | null;
                    to_email: string;
                    from_email: string;
                    subject: string | null;
                    status: EmailStatus;
                    smtp_response: string | null;
                    message_id: string | null;
                    error_message: string | null;
                    sent_at: string | null;
                    delivered_at: string | null;
                    opened_at: string | null;
                    clicked_at: string | null;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    user_id: string;
                    campaign_id?: string | null;
                    lead_id?: string | null;
                    to_email: string;
                    from_email: string;
                    subject?: string | null;
                    status?: EmailStatus;
                    smtp_response?: string | null;
                    message_id?: string | null;
                    error_message?: string | null;
                    sent_at?: string | null;
                    delivered_at?: string | null;
                    opened_at?: string | null;
                    clicked_at?: string | null;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    user_id?: string;
                    campaign_id?: string | null;
                    lead_id?: string | null;
                    to_email?: string;
                    from_email?: string;
                    subject?: string | null;
                    status?: EmailStatus;
                    smtp_response?: string | null;
                    message_id?: string | null;
                    error_message?: string | null;
                    sent_at?: string | null;
                    delivered_at?: string | null;
                    opened_at?: string | null;
                    clicked_at?: string | null;
                    created_at?: string;
                };
            };
            site_settings: {
                Row: {
                    id: string;
                    key: string;
                    value: string | null;
                    type: string;
                    description: string | null;
                    is_public: boolean;
                    updated_by: string | null;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    key: string;
                    value?: string | null;
                    type?: string;
                    description?: string | null;
                    is_public?: boolean;
                    updated_by?: string | null;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    key?: string;
                    value?: string | null;
                    type?: string;
                    description?: string | null;
                    is_public?: boolean;
                    updated_by?: string | null;
                    updated_at?: string;
                };
            };
            whatsapp_templates: {
                Row: {
                    id: string;
                    user_id: string;
                    name: string;
                    message: string;
                    is_default: boolean;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    user_id: string;
                    name: string;
                    message: string;
                    is_default?: boolean;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    user_id?: string;
                    name?: string;
                    message?: string;
                    is_default?: boolean;
                    created_at?: string;
                    updated_at?: string;
                };
            };
        };
    };
}

// Helper types for components
export type UserProfile = Database['public']['Tables']['user_profiles']['Row'];
export type Lead = Database['public']['Tables']['leads']['Row'];
export type LeadSearch = Database['public']['Tables']['lead_searches']['Row'];
export type EmailTemplate = Database['public']['Tables']['email_templates']['Row'];
export type EmailCampaign = Database['public']['Tables']['email_campaigns']['Row'];
export type SmtpConfig = Database['public']['Tables']['smtp_configs']['Row'];
export type SubscriptionPlan = Database['public']['Tables']['subscription_plans']['Row'];
export type WhatsAppTemplate = Database['public']['Tables']['whatsapp_templates']['Row'];

// Blog Post types
export interface BlogPost {
    id: string;
    title: string;
    slug: string;
    excerpt: string | null;
    content: string;
    featured_image: string | null;
    author_name: string;
    category: string | null;
    tags: string[];
    meta_title: string | null;
    meta_description: string | null;
    meta_keywords: string | null;
    og_image: string | null;
    is_published: boolean;
    is_featured: boolean;
    view_count: number;
    read_time_minutes: number;
    published_at: string | null;
    created_at: string;
    updated_at: string;
}

export interface BlogView {
    id: string;
    blog_id: string;
    visitor_ip: string | null;
    user_agent: string | null;
    referrer: string | null;
    country: string | null;
    city: string | null;
    viewed_at: string;
}

